name: Build Ghidrathon

on:
  push:
  pull_request:

jobs:
  build_extensions:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ghidra: ['latest']
        gradle-version: ['7.3']
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build jep
      run: pip install jep

    - name: Set Ghidra version
      run: |
        if [ ${{ matrix.ghidra }} = latest ]; then
            ghidra_version=$(curl -fLsSo /dev/null -w %{url_effective} https://github.com/NationalSecurityAgency/ghidra/releases/latest |
            grep -oP '(?<=https://github.com/NationalSecurityAgency/ghidra/releases/tag/Ghidra_).+(?=_build)')
            echo "ghidra_version=$ghidra_version" >> $GITHUB_ENV
        else
            echo "ghidra_version=${{ matrix.ghidra }}" >> $GITHUB_ENV
        fi

    - name: Setup Ghidra
      uses: er28-0652/setup-ghidra@master
      with:
        version: ${{ env.ghidra_version }}

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Build Ghidrathon
      uses: gradle/gradle-build-action@main
      with:
        gradle-version: ${{ matrix.gradle-version }}
        build-root-directory: .
        arguments: -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}

    - name: Upload Ghidrathon Artifact
      uses: actions/upload-artifact@v3
      with:
        path: dist/*.zip
        if-no-files-found: error
        retention-days: 14

  push_release:
    needs: build_extensions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create 1.0${{ GITHUB.RUN_NUMBER }} artifact/*.zip --target ${{ GITHUB.SHA }} -t 1.0${{ GITHUB.RUN_NUMBER }}
